trigger:
- develop

pool:
  vmImage: 'ubuntu-16.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'


steps:

- task: UseDotNet@2
  inputs:
    version: '3.1.x'
    packageType: sdk


- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      docker --version
      cd IntegrationAdapters
      dotnet publish IntegrationAdapters.csproj -c Release -o publish
      cp Dockerfile publish

- task: Docker@2
  inputs:
    containerRegistry: 'DockerConnection'
    repository: 'budjenvladimir/health_clinic_integration_adapters'
    command: 'buildAndPush'
    Dockerfile: 'IntegrationAdapters/publish/Dockerfile'
    buildContext: 'IntegrationAdapters/publish'
    tags: |
      $(Build.BuildId)
      latest

